### ISSUE TITLE
`yaqd-fakes`: install does not properly register entry points for some daemons

### ISSUE THREAD

**Issue by ddkohler** [yaq-project/yaq-python#76]
Apologies if this is a problem with my particular setup.  I have installed `yaqd-fakes` in it's own environment:
```
conda create -n yaq yaqd-fakes python=3.11
```
My computer cannot find the entry point for `yaqd-fake-has-transformed-position`.  In the terminal:
```
(yaq) ...> yaqd-fake-has-transformed-position
'yaqd-fake-has-transformed-position' is not recognized as an internal or external command, operable program or batch file.
```
It can find and start other daemons like `fake-sensor`.  

In the `Scripts` folder of the environment, I also see an issue as the filename suffixes
```
> dir
...
11/09/2023  03:43 PM               301 yaqd-fake-furnace
11/09/2023  03:43 PM               348 yaqd-fake-has-transformed-position
11/09/2023  03:43 PM               233 yaqd-fake-has-turret-script.py
09/12/2023  05:15 AM            41,984 yaqd-fake-has-turret.exe
11/09/2023  03:43 PM               223 yaqd-fake-sensor-script.py
09/12/2023  05:15 AM            41,984 yaqd-fake-sensor.exe
...
```

Daemons without filepath suffixes also do not have working entry-points. 

I am puzzled why some daemons have installed just fine while others have not; nothing obvious jumps out at me in the pyproject.toml file.  Any insights are greatly appreciated!

**Comment by ksunden** [comment]
Conda packages have an alternate list of entry points, see conda-forge/yaqd-fakes-feedstock#21 (PR which adds the missing entries)

Installing from pip/source would also install the entry points in the mean time...
